version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: nsfminer-v1

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.hunter
          key: nsfminer-v1

  build:
    steps:
      - run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
      - run: echo $TZ > /etc/timezone
      - run: apt update
      - run: apt install -y git cmake mesa-common-dev
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache_cmd
      - run: cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON -DETHDBUS=ON -DDEVBUILD=ON -DETHASHCPU=ON -H. -Bbuild
      - save_cache_cmd
      - run: cmake --build build -- -j4
      - store_artifacts:
          path: build/nsfminer/nsfminer
          destination: nsfminer

executors:
 docker-executor-u20n11:
   docker:
     - image: nvidia/cuda:11.0-devel-ubuntu20.04

 docker-executor-u18n10:
   docker:
     - image: nvidia/cuda:10.2-devel-ubuntu18.04

jobs:
  build-with-docker-u20n11:
    executor: docker-executor-u20n11
    steps:
      - build
    environment:
        TZ: "America/New_York"

  build-with-docker-u18n10:
    executor: docker-executor-u18n10
    steps:
      - build
    environment:
        TZ: "America/New_York"

workflows:
  build-with-docker:
    jobs:
      - build-with-docker-u20n11

